import Link from "next/link";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { hasSupabaseEnv } from "@/lib/supabase/config";

export default function Page() {
  const local = !hasSupabaseEnv();
  return <main className="min-h-dvh bg-[var(--aera-ivory)] px-5 py-8 sm:px-8"><div className="mx-auto flex min-h-[calc(100dvh-4rem)] max-w-6xl flex-col"><nav className="flex items-center justify-between"><span className="text-2xl font-bold tracking-[.16em]">AERA</span><Link href={local ? "/home" : "/login"} className="text-sm font-bold">{local ? "Open demo" : "Sign in"}</Link></nav><section className="grid flex-1 items-center gap-12 py-16 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-[11px] font-bold uppercase tracking-[.17em] text-[var(--aera-terracotta)]">Fitness · nutrition · recovery</p><h1 className="mt-5 max-w-[11ch] text-[52px] font-bold leading-[.97] tracking-[-.055em] sm:text-[76px]">Understand your body. Become your best.</h1><p className="mt-7 max-w-xl text-base leading-7 text-black/60">A practical coaching system with deterministic plans, transparent recommendations and safety-first health guidance.</p><div className="mt-8 flex flex-wrap gap-3"><Link href={local ? "/home" : "/signup"} className="flex min-h-13 items-center gap-2 rounded-lg bg-[var(--aera-terracotta)] px-6 text-base font-bold text-white">{local ? "Explore the working demo" : "Create your plan"}<ArrowRight size={18} /></Link><Link href="/training/exercises" className="flex min-h-13 items-center rounded-lg border border-black/15 bg-white px-6 text-base font-bold">Browse exercises</Link></div>{local && <p className="mt-5 flex items-center gap-2 text-xs text-black/50"><ShieldCheck size={15} /> Local mode: no account required; changes stay on this device.</p>}</div><div className="relative mx-auto aspect-[4/5] w-full max-w-md overflow-hidden rounded-[2rem] bg-[var(--aera-forest)] p-7 text-white shadow-2xl"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-white/55">Today with AERA</p><h2 className="mt-3 text-3xl font-bold">Clear next steps.</h2><div className="mt-8 space-y-3"><Card title="Train" value="Upper body · 45 min" /><Card title="Eat" value="1,840 of 2,200 kcal" /><Card title="Recover" value="7h 32m sleep" /><Card title="Review" value="On track this week" /></div></div></section></div></main>;
}

function Card({ title, value }: { title: string; value: string }) { return <div className="rounded-xl bg-white/10 p-4 backdrop-blur"><p className="text-[9px] font-bold uppercase tracking-[.13em] text-white/45">{title}</p><p className="mt-1 font-bold">{value}</p></div>; }
